const catalog={
"1":{name:"Urban Flex Sneakers",category:"SNEAKERS",price:8999,image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1100&q=90"},
"2":{name:"Royal Oxford Formal",category:"FORMAL SHOES",price:12499,image:"https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=1100&q=90"},
"3":{name:"Classic Chelsea Boots",category:"CHELSEA BOOTS",price:13499,image:"https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=1100&q=90"},
"4":{name:"Nova White Sneakers",category:"SNEAKERS",price:9499,image:"https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=1100&q=90"},
"5":{name:"Elite Derby Formal",category:"FORMAL SHOES",price:11499,image:"https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=1100&q=90"},
"6":{name:"Suede Chelsea",category:"CHELSEA BOOTS",price:12999,image:"https://images.unsplash.com/photo-1520639888713-7851133b0e72?auto=format&fit=crop&w=1100&q=90"}
};
const id=new URLSearchParams(location.search).get('id')||'1',p=catalog[id];
document.getElementById('productName').textContent=p.name;document.getElementById('productCategory').textContent=p.category;document.getElementById('productPrice').textContent='Rs. '+p.price.toLocaleString('en-PK');document.getElementById('productImage').src=p.image;document.getElementById('productImage').alt=p.name;
let size='';document.querySelectorAll('#sizes button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#sizes button').forEach(x=>x.classList.remove('selected-size'));b.classList.add('selected-size');size=b.textContent;document.getElementById('sizeNote').textContent='Selected size: '+size}));
let cart=JSON.parse(localStorage.getItem('novaCart')||'[]');
function render(){document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+(x.qty||1),0)}
function renderCart(){const box=document.getElementById('cartItems');box.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><img src="${x.image}" alt="${x.name}"><div class="cart-product-info"><h4>${x.name}</h4><p>${x.priceText}${x.size?' • Size '+x.size:''}</p><div class="qty-controls"><button onclick="changeQty(${i},-1)">−</button><span>${x.qty||1}</span><button onclick="changeQty(${i},1)">+</button></div></div><button class="remove-item" onclick="removeCart(${i})">×</button></div>`).join(''):'<p class="empty-cart">Your cart is empty.</p>';document.getElementById('cartTotal').textContent='Rs. '+cart.reduce((s,x)=>s+x.price*(x.qty||1),0).toLocaleString('en-PK')}
window.changeQty=(i,d)=>{cart[i].qty=Math.max(1,(cart[i].qty||1)+d);localStorage.setItem('novaCart',JSON.stringify(cart));render();renderCart()};window.removeCart=i=>{cart.splice(i,1);localStorage.setItem('novaCart',JSON.stringify(cart));render();renderCart()};
document.getElementById('addProduct').addEventListener('click',()=>{if(!size){document.getElementById('sizeNote').textContent='Please select a size first.';return}const same=cart.find(x=>x.id===id&&String(x.size)===String(size));if(same)same.qty=(same.qty||1)+1;else cart.push({id,name:p.name,price:p.price,priceText:'Rs. '+p.price.toLocaleString('en-PK'),image:p.image,size,qty:1});localStorage.setItem('novaCart',JSON.stringify(cart));render();document.getElementById('toast').textContent=p.name+' — size '+size+' added to cart';document.getElementById('toast').classList.add('show');setTimeout(()=>document.getElementById('toast').classList.remove('show'),1700);document.getElementById('cartPanel').classList.add('open');renderCart()});
document.querySelector('.cart-btn').addEventListener('click',()=>{renderCart();document.getElementById('cartPanel').classList.add('open')});document.getElementById('closeCart').addEventListener('click',()=>document.getElementById('cartPanel').classList.remove('open'));document.getElementById('checkoutBtn').addEventListener('click',()=>{if(cart.length)location.href='checkout.html';else{document.getElementById('toast').textContent='Your cart is empty';document.getElementById('toast').classList.add('show');setTimeout(()=>document.getElementById('toast').classList.remove('show'),1700)}});render();renderCart();
